### ISSUE TITLE
The lib does not support HTTPS mode

### ISSUE THREAD

**Issue by Guotman** [etsi-cti-admin/robotframework-mockserver#2] opened 2020-08-27 16:08 UTC
Hi, 

It would be nice to be able to pass headers when creating a mock session in order to pass a certificate

**Comment by michele-carignani** [comment] 2020-08-28 13:33
Hi @Guotman ,

Thanks for reporting. Could you please clarify your use case? In particular, which among the cases described here
https://www.mock-server.com/mock_server/HTTPS_TLS.html?

**Comment by michele-carignani** [comment] 2021-01-20 08:21
Closing due to missing details. Feel free to reopen and include details on the expected behaviour.

**Closed as completed by michele-carignani** 2021-01-20 08:21 UTC
